site_name: Yeeps Redstone
site_url: https://lrutjens.github.io
theme:
  name: material
  logo: assets/logo-transparent.png
  favicon: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-2
        name: Dark Mode
    - media: "(prefers-color-scheme: light)"
      scheme: custom
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Light Mode
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - content.code.annotate
    - content.tooltips
markdown_extensions:
  - attr_list
  - md_in_html
  - toc
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr
  - attr_list
  - pymdownx.snippets
plugins:
  - glightbox
nav:
  - Getting Started:
    - index.md
    - Logic Gates: gates.md
    - Interactables: interactables.md
    - Traps: traps.md
    - Triggers: triggers.md
    - Wiring: wiring.md
    - Yessembly: yeessembly.md
    - Legacy:
      - Intro: legacy/index.md
      - Bomb Gates: legacy/bomb-gates.md
      - Icicle Gates: legacy/icicle-gates.md
    - Contributing: contributing.md
  - Yeessembly:
    - Documentation: yeessembly.md
    - Yeessembler: yeessembler.md
extra:
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/yBR9rNVrNc
      name: Yeeps Redstone Discord
extra_css:
  - stylesheets/extra.css