site_name: Yeeps Redstone
site_url: https://lrutjens.github.io
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - content.code.annotate
    - content.tooltips
markdown_extensions:
  - attr_list
  - md_in_html
  - toc
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - abbr
  - attr_list
  - pymdownx.snippets
plugins:
  - glightbox
nav:
  - Getting Started:
    - index.md
    - Logic Gates: gates.md
    - Interactables: interactables.md
    - Traps: traps.md
    - Triggers: triggers.md
    - Wiring: wiring.md
    - Documentation: yeessembly.md
    - Yeessembler: yeessembler.md
    - Legacy:
      - Intro: legacy/index.md
      - Bomb Gates: legacy/bomb-gates.md
      - Icicle Gates: legacy/icicle-gates.md
    - Contributing: contributing.md
  - Yeessembly:
    - Documentation: yeessembly.md
    - Yeessembler: yeessembler.md
